-------------------------------------------------------------------------------
Test set: fr.ensea.rts.kardellas.suprano.server.UDPServerTest
-------------------------------------------------------------------------------
Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.023 s <<< FAILURE! -- in fr.ensea.rts.kardellas.suprano.server.UDPServerTest
fr.ensea.rts.kardellas.suprano.server.UDPServerTest.testServerLaunchInvalidPort -- Time elapsed: 0.006 s <<< FAILURE!
org.opentest4j.AssertionFailedError: Cause of exception should be a SocketException. ==> expected: <true> but was: <false>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertTrue.failNotTrue(AssertTrue.java:63)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:36)
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:214)
	at fr.ensea.rts.kardellas.suprano.server.UDPServerTest.testServerLaunchInvalidPort(UDPServerTest.java:59)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)

